# Generated by Django 2.0.2 on 2018-03-11 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('RequestID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('isAccepted', models.BooleanField(default=False)),
                ('IncidentType', models.CharField(max_length=200)),
                ('Image', models.CharField(max_length=100000, null=True)),
                ('LatLonTuple', models.CharField(max_length=50)),
                ('Details', models.CharField(max_length=1000, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('StationID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('StaionName', models.CharField(max_length=200)),
                ('StationArea', models.CharField(max_length=200)),
                ('LatLonTuple', models.CharField(max_length=50)),
                ('SPOCUsername', models.CharField(max_length=100)),
                ('SPOCPassword', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='AcceptedFrom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='serve.Station'),
        ),
    ]
