# Generated by Django 2.0.2 on 2018-03-11 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serve', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='StaionName',
            new_name='StationName',
        ),
    ]
