# Generated by Django 2.0.2 on 2018-03-11 18:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('serve', '0003_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Count',
        ),
        migrations.AddField(
            model_name='request',
            name='DeviceID',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
